/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'outline-variant': '#c3c6d7',
        'surface-variant': '#d5e3fc',
        'tertiary-container': '#6b6e70',
        'on-tertiary-fixed': '#191c1e',
        'on-tertiary-container': '#eff1f3',
        'surface-container-low': '#eff4ff',
        'secondary-container': '#82f5c1',
        'inverse-on-surface': '#eaf1ff',
        'on-surface': '#0d1c2e',
        'outline': '#737686',
        'on-primary-fixed-variant': '#003ea8',
        'on-secondary-fixed': '#002114',
        'surface-tint': '#0053db',
        'inverse-surface': '#233144',
        'on-secondary': '#ffffff',
        'surface': '#f8f9ff',
        'inverse-primary': '#b4c5ff',
        'secondary-fixed-dim': '#68dba9',
        'secondary-fixed': '#85f8c4',
        'background': '#f8f9ff',
        'primary': '#004ac6',
        'secondary': '#006c4a',
        'on-error-container': '#93000a',
        'on-secondary-fixed-variant': '#005137',
        'error-container': '#ffdad6',
        'on-primary-fixed': '#00174b',
        'surface-bright': '#f8f9ff',
        'on-surface-variant': '#434655',
        'error': '#ba1a1a',
        'on-background': '#0d1c2e',
        'surface-dim': '#ccdbf3',
        'on-tertiary': '#ffffff',
        'surface-container-highest': '#d5e3fc',
        'primary-fixed': '#dbe1ff',
        'on-primary-container': '#eeefff',
        'surface-container-lowest': '#ffffff',
        'primary-container': '#2563eb',
        'surface-container': '#e6eeff',
        'tertiary-fixed': '#e0e3e5',
        'on-error': '#ffffff',
        'on-secondary-container': '#00714e',
        'on-tertiary-fixed-variant': '#444749',
        'surface-container-high': '#dce9ff',
        'tertiary': '#525657',
        'tertiary-fixed-dim': '#c4c7c9',
        'on-primary': '#ffffff',
        'primary-fixed-dim': '#b4c5ff',
      },
      fontFamily: {
        display: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'display-lg-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
      spacing: {
        'base': '4px',
        'lg': '24px',
        'sm': '8px',
        'container-max': '1280px',
        'xs': '4px',
        'md': '16px',
        'gutter': '24px',
        'xl': '40px',
        'margin-mobile': '20px',
        'margin-desktop': '64px',
      },
    },
  },
  plugins: [],
}